version: "3.9"

services:
  api:
    build: .
    container_name: leadgen-api
    command: sh -c "alembic upgrade head && uvicorn api.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    environment:
      - USE_DB=${USE_DB:-false}
      - DATABASE_URL=${DATABASE_URL:-postgresql+asyncpg://postgres:postgres@db:5432/leadgen}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-devsecret}
      - DOCUSEAL_API_KEY=${DOCUSEAL_API_KEY}
      - DOCUSEAL_TEMPLATE_ID=${DOCUSEAL_TEMPLATE_ID:-}
      - DOCUSEAL_FORM_BASE=${DOCUSEAL_FORM_BASE:-https://docuseal.com}
      - DOCUSEAL_API_BASE=${DOCUSEAL_API_BASE:-https://api.docuseal.com}
    depends_on:
      - redis
      - db

  redis:
    image: redis:7
    container_name: leadgen-redis
    ports:
      - "6379:6379"

  db:
    image: postgres:15
    container_name: leadgen-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=leadgen
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

